apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'com.mobeen.amrapali'
    compileSdk 34

    defaultConfig {
        applicationId "com.mobeen.amrapali"
        minSdk 21
        targetSdk 34
        versionCode 3
        versionName "1.2"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
